routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('category');
//    return view('master');
//});

//index page 
Route::get('/', 'WelcomeController@index');

Auth::routes();
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');


Route::get('/home', 'HomeController@index')->name('home');


//admin panel
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    //password reset route
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    //header
    Route::resource('header', 'HeaderController');
    //category
    Route::resource('category', 'CategoriesController');

    //suggestion
    Route::resource('suggestion', 'SuggestionController');
    //physics
    Route::resource('physic', 'PhysicController');
    //notice
    Route::resource('notice', 'NoticeController');
    //class sheets
    Route::resource('sheet', 'ClassSheetController');
    //about
    Route::resource('about', 'AboutController');
    //contact
    Route::resource('contact', 'ContactController');
    //ict
    Route::resource('ict', 'IctController');


});
//manage single category page and post
Route::get('single/{id}', 'SingleController@show');
Route::resource('page', 'PageController', ['only' => 'show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/ClassSheet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ClassSheet extends Model
{
    protected $table='class_sheets';
}

app/Http/Controllers/ClassSheetController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\ClassSheet;
use Illuminate\Support\Facades\Storage;
use Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ClassSheetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sheets= ClassSheet::orderBy('id','desc')->get();
        return view('class_sheets.index')->withSheets($sheets);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('class_sheets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'description'=>'required',
            'image'=>'sometimes'
        ]);



        $sheet= new ClassSheet();
        $sheet->title= $request->title;
        $sheet->description= $request->description;

        if($request->hasFile('image')){
            $image=$request->file('image');
            $file_name=time().'.'.$image->getClientOriginalExtension();
            $location=public_path('images/'.$file_name);
            Image::make($image)->save($location);
            $sheet->image=$file_name;
        }
        $sheet->publication_status=$request->publication_status;

        $sheet->save();

        Session::flash('message','Data insert Successfully');
        return redirect()->route('sheet.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sheet= ClassSheet::findOrFail($id);
        return view('class_sheets.show')->withSheet($sheet);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sheet= ClassSheet::find($id);
        return view('class_sheets.edit')->withSheet($sheet);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $sheet = ClassSheet::findOrFail($id);
        $sheet->title=$request->title;
        $sheet->description=$request->description;
        if($request->hasFile('image')){
            $image=$request->file('image');
            $file_name=time().".".$image->getClientOriginalExtension();
            $location=public_path('images/'.$file_name);
            Image::make($image)->save($location);
            $old_file=$sheet->image;
            $sheet->image=$file_name;
            Storage::delete($old_file);
        }
        $sheet->publication_status=$request->publication_status;
        $sheet->update();

        Session::flash('message','Data update Successfully');
        return redirect()->route('sheet.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sheet= ClassSheet::findOrFail($id);
        Storage::delete($sheet->image);
        $sheet->delete();
        Session::flash('message','data deleted successfully');
        return redirect()->route('sheet.index');
    }
}

resources/views/class_sheets/create.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book">CREATE CLASS SHEET</i></div>
        <div class="panel-body">
    {!! Form::open(['route'=>['sheet.store'],'files'=>true]) !!}
    <!-- Title Form Input -->
    <div class="form-group">
        {{Form::label('title','Title:')}}
        {{Form::text('title',null,['class'=>'form-control'])}}
    </div>
    <!-- Description Form Input -->
    <div class="form-group">
        {{Form::label('description','Description:')}}
        {{Form::text('description',null,['class'=>'form-control'])}}
    </div>
    <!-- Image Form Input -->
    <div class="form-group">
        {{Form::label('image','Image:')}}
        {{Form::file('image',null,['class'=>'form-control'])}}
    </div>
    <!-- Publication_status Form Input -->
    <div class="form-group">
        {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}
    </div>
    {{Form::submit('save',['class'=>'btn btn-success btn-sm'])}}
    <a href="{{route('suggestion.index')}}" class="btn btn-danger btn-sm">Cancel</a>
    {!! Form::close() !!}
        </div>
        </div>
@endsection

resources/views/class_sheets/edit.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book">EDIT SHEET</i></div>
        <div class="panel-body">
    {!! Form::model($sheet,['route'=>['sheet.update',$sheet->id], 'method'=>'PUT', 'files'=>true]) !!}
    <!-- Title Form Input -->
    <div class="form-group">
        {{Form::label('title','Title:')}}
        {{Form::text('title',null,['class'=>'form-control'])}}
    </div>
    <!-- Description Form Input -->
    <div class="form-group">
        {{Form::label('description','Description:')}}
        {{Form::text('description',null,['class'=>'form-control'])}}
    </div>
    <!--old image-->
    <div class="form-group">
        <h4>old images</h4>
        <img src="{{asset('images/'.$sheet->image)}}" alt="" height="200" width="300">
    </div>
    <!-- Image Form Input -->
    <div class="form-group">
        {{Form::label('image','Image:')}}
        {{Form::file('image',null,['class'=>'form-control'])}}
    </div>
    <!-- Publication_status Form Input -->
    <div class="form-group">
        {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}

    </div>
    {{Form::submit('update',['class'=>'btn btn-success btn-sm'])}}
    {!! Form::close() !!}
        <a href="{{route('sheet.index')}}" class="fa fa-arrow-left btn btn-info btn-sm"> back</a>
        {!! Form::open(['route'=>['sheet.destroy',$sheet->id],'method'=>'DELETE']) !!}
        {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
        {!! Form::close() !!}

        </div>
        </div>
@endsection

resources/views/class_sheets/index.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book">CLASS SHEETS</i></div>
        <div class="panel-body">
    <a href="{{route('sheet.create')}}" class="text-success"><b>ADD NEW+</b></a>
<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <th>Title</th>
            <th>Details</th>
            <th>image</th>
            <th>status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($sheets as $sheet)
    <tr>
        <td>{{$sheet->title}}</td>
        <td class="col-sm-6">{{$sheet->description}}</td>
        <td><img src="{{asset('images/'.$sheet->image)}}" alt="" width="50" height="50"></td>
        <td>
            @if($sheet->publication_status==1)
                <span class="fa fa-thumbs-o-up text-success">publish</span>
            @else
                <span class="fa fa-thumbs-o-down text-danger">un publish</span>
            @endif

        </td>
        <td>
            {!! HTML::decode(Html::linkRoute('sheet.show','<i class="fa fa-eye">view</i>', [$sheet->id],['style'=>'margin:5px; float:left'])) !!}
            {!! HTML::decode(Html::linkRoute('sheet.edit','<i class="fa fa-pencil-square-o">edit</i>', [$sheet->id],['style'=>'margin:5px; float:left'])) !!}
            {!! Form::open(['route'=>['sheet.destroy',$sheet->id],'method'=>'DELETE']) !!}
            {{  Form::button( '<i class="fa fa-trash-o"></i>', ['type' => 'submit','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
            {!! Form::close() !!}
        </td>
    </tr>
        @endforeach
    </tbody>
</table>

    </div>
    </div>
@endsection

resources/views/class_sheets/show.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book">VIEW SHEET</i></div>
        <div class="panel-body">
    <h3>{{$sheet->title}}</h3>
    <p>{{$sheet->description}}</p>
    <img src="{{asset('images/'.$sheet->image)}}" alt="" width="300" height="300" style="float: left">

        </div>
        <div class="panel-footer">
            <a href="{{route('sheet.index')}}" class="fa fa-arrow-left btn btn-info btn-sm" style="float: left;">back</a>
            {!! HTML::decode(Html::linkRoute('sheet.edit','<i class="fa fa-pencil-square-o btn btn-warning">edit</i>', [$sheet->id],['style'=>'margin:0 5px; float:left'])) !!}
            {!! Form::open(['route'=>['sheet.destroy',$sheet->id],'method'=>'DELETE']) !!}
            {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection