routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('category');
//    return view('master');
//});

//index page 
Route::get('/', 'WelcomeController@index');

Auth::routes();
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');


Route::get('/home', 'HomeController@index')->name('home');


//admin panel
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    //password reset route
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    //header
    Route::resource('header', 'HeaderController');
    //category
    Route::resource('category', 'CategoriesController');

    //suggestion
    Route::resource('suggestion', 'SuggestionController');
    //physics
    Route::resource('physic', 'PhysicController');
    //notice
    Route::resource('notice', 'NoticeController');
    //class sheets
    Route::resource('sheet', 'ClassSheetController');
    //about
    Route::resource('about', 'AboutController');
    //contact
    Route::resource('contact', 'ContactController');
    //ict
    Route::resource('ict', 'IctController');


});
//manage single category page and post
Route::get('single/{id}', 'SingleController@show');
Route::resource('page', 'PageController', ['only' => 'show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Physic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Physic extends Model
{
   protected $table='physics';
}

app/Http/Controllers/PhysicController.php
<?php

namespace App\Http\Controllers;


use App\Physic;
use Illuminate\Support\Facades\Storage;
use Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class PhysicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $physics= Physic::orderBy('id','desc')->get();
        return view('physics.index')->withPhysics($physics);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('physics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $this->validate($request,[
            'title'=>'required',
            'description'=>'required',
            'image'=>'sometimes',
            'video'=>'sometimes',
            'paper'=>'required',
            'chapter'=>'required',
            'publication_status'=>'required'

        ]);

        $physic= new Physic();
        $physic->title= $request->title;
        $physic->description= $request->description;

        if($request->hasFile('image')){
            $image=$request->file('image');
            $file_name=time().'.'.$image->getClientOriginalExtension();
            $location=public_path('images/'.$file_name);
            Image::make($image)->save($location);
            $physic->image=$file_name;
        }
        $physic->video=substr($request->video,32);
        $physic->paper=$request->paper;
        $physic->chapter=$request->chapter;
        $physic->publication_status=$request->publication_status;

        $physic->save();

        Session::flash('message','Data insert Successfully');
        return redirect()->route('physic.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $physic= Physic::findOrFail($id);
        return view('physics.show')->withphysic($physic);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $physic= Physic::find($id);
        return view('physics.edit')->withphysic($physic);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $physic = Physic::findOrFail($id);
        $physic->title=$request->title;
        $physic->description=$request->description;
        if($request->hasFile('image')){
            $image=$request->file('image');
            $file_name=time().".".$image->getClientOriginalExtension();
            $location=public_path('images/'.$file_name);
            Image::make($image)->save($location);
            $old_file=$physic->image;
            $physic->image=$file_name;
            Storage::delete($old_file);
        }
        $physic->video=substr($request->video,32);
        $physic->chapter=$request->chapter;
        $physic->publication_status=$request->publication_status;
        $physic->update();

        Session::flash('message','Data update Successfully');
        return redirect()->route('physic.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $physic= physic::findOrFail($id);
        Storage::delete($physic->image);
        $physic->delete();
        Session::flash('message','data deleted successfully');
        return redirect()->route('physic.index');
    }
}

resources/views/physics/create.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book"> CREATE PHYSICS TOPIC </i></div>
        <div class="panel-body">
        {!! Form::open(['route'=>['physic.store'],'files'=>true]) !!}
        <!-- Title Form Input -->
            <div class="form-group">
                {{Form::label('title','Title:')}}
                {{Form::text('title',null,['class'=>'form-control'])}}
            </div>
            <!-- Description Form Input -->
            <div class="form-group">
                {{Form::label('description','Description:')}}
                {{Form::text('description',null,['class'=>'form-control'])}}
            </div>
            <!-- Image Form Input -->
            <div class="form-group">
                {{Form::label('image','Image:')}}
                {{Form::file('image',null,['class'=>'form-control'])}}
            </div>
            <!-- Video Form Input -->
            <div class="form-group">
                {{Form::label('video','Video:')}}
                {{Form::text('video',null,['class'=>'form-control'])}}
            </div>
            <!--select part-->
            <div class="form-group">
               {{ Form::select('paper', ['1' => 'First Paper', '2' => 'Second Paper'], null, ['class'=>'form-control','placeholder' => 'select paper.'])}}
            </div>
            <!-- Chapter Form Input -->
            <div class="form-group">
                {{Form::label('chapter','Chapter:')}}
                {{Form::text('chapter',null,['class'=>'form-control'])}}
            </div>
            <!-- Publication_status Form Input -->
            <div class="form-group">
                {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}
            </div>
            {{Form::submit('save',['class'=>'btn btn-success btn-sm'])}}
            <a href="{{route('physic.index')}}" class="btn btn-danger btn-sm">Cancel</a>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/physics/edit.blade.php
@extends('admin')
@section('main-content')
<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-book"> EDIT PHYSICS</i></div>
    <div class="panel-body">
        {!! Form::model($physic,['route'=>['physic.update',$physic->id], 'method'=>'PUT', 'files'=>true]) !!}
        <!-- Title Form Input -->
        <div class="form-group">
            {{Form::label('title','Title:')}}
            {{Form::text('title',null,['class'=>'form-control'])}}
        </div>
        <!-- Description Form Input -->
        <div class="form-group">
            {{Form::label('description','Description:')}}
            {{Form::text('description',null,['class'=>'form-control'])}}
        </div>


        <!--old image-->
        <div class="form-group">
            <h4>old images</h4>
            <img src="{{asset('images/'.$physic->image)}}" alt="" height="200" width="300">
        </div>
        <!-- Image Form Input -->
        <div class="form-group">
            {{Form::label('image','Image:')}}
            {{Form::file('image',null,['class'=>'form-control'])}}
        </div>
        {{--old video link--}}
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{$physic->video}}" frameborder="0" allowfullscreen></iframe>
        <!-- Video Form Input -->
        <div class="form-group">
            {{Form::label('paper','Paper')}}
            {{Form::text('paper',null,['class'=>'form-control'])}}
        </div>
     <div class="form-group">
        {{Form::label('chapter','Chapter')}}
            {{Form::text('chapter',null,['class'=>'form-control'])}}
    </div>
        <div class="form-group">
            {{Form::label('video','Video:')}}
            {{Form::text('video',null,['class'=>'form-control'])}}
        </div>

        <!-- Publication_status Form Input -->
        <div class="form-group">
            {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}

        </div>
        {{Form::submit('update',['class'=>'btn btn-success btn-sm'])}}
        {!! Form::close() !!}
        <a href="{{route('ict.index')}}" class="fa fa-arrow-left btn btn-info btn-sm"> back</a>
        {!! Form::open(['route'=>['physic.destroy',$physic->id],'method'=>'DELETE']) !!}
        {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
        {!! Form::close() !!}

    </div>
</div>
@endsection

resources/views/physics/index.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book"> PHYSICS </i></div>
        <div class="panel-body">
            <a href="{{route('physic.create')}}" class="text-success"><b>ADD NEW+</b></a>
            <table class="table table-bordered table-responsive">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Details</th>
                    <th>image</th>
                    <th>paper</th>
                    <th>status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($physics as $physic)
                    <tr>
                        <td>{{$physic->title}}</td>
                        <td class="col-sm-6">{{$physic->description}}</td>
                        <td><img src="{{asset('images/'.$physic->image)}}" alt="" width="50" height="50"></td>
                        <td>{{$physic->paper}}</td>
                        <td>
                            @if($physic->publication_status==1)
                                <span class="fa fa-thumbs-o-up text-success">publish</span>
                            @else
                                <span class="fa fa-thumbs-o-down text-danger">un publish</span>
                            @endif

                        </td>
                        <td>
                            {!! HTML::decode(Html::linkRoute('physic.show','<i class="fa fa-eye">view</i>', [$physic->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! HTML::decode(Html::linkRoute('physic.edit','<i class="fa fa-pencil-square-o">edit</i>', [$physic->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Form::open(['route'=>['physic.destroy',$physic->id],'method'=>'DELETE']) !!}
                            {{  Form::button( '<i class="fa fa-trash-o"></i>', ['type' => 'submit','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
    </div>
@endsection

resources/views/physics/show.blade.php
@extends('admin')
@section('main-content')
    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-book"> VIEW PHYSICS </i></div>
        <div class="panel-body">
    <h3>{{$ict->title}}</h3>
    <p>{{$ict->description}}</p>
    <img src="{{asset('images/'.$physic->image)}}" alt="" width="300" height="300" style="float: left">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/{{$physic->video}}" frameborder="0" allowfullscreen></iframe>
        </div>
        <div class="panel-footer">
            <a href="{{route('physic.index')}}" class="fa fa-arrow-left btn btn-info btn-sm" style="float: left;">back</a>
            {!! HTML::decode(Html::linkRoute('physic.edit','<i class="fa fa-pencil-square-o btn btn-warning">edit</i>', [$ict->id],['style'=>'margin:0 5px; float:left'])) !!}
            {!! Form::open(['route'=>['physic.destroy',$physic->id],'method'=>'DELETE']) !!}
            {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection